= Noise generator
:icons: font

Generate a WAV file with noise of specified color.

It generates noise in small chunks and then overlaps them with a window function to avoid sharp transitions and artifacts like frequency and volume pulsations.

== Usage

```
Usage: noise-generator [OPTIONS] [COLOR]

Arguments:
  [COLOR]  Noise color [possible values: white, pink, red, blue, violet, grey]

Options:
  -g, --generator <GENERATOR>  Noise generator [default: olap] [possible values: phc, olap]
  -o, --output <WAV_FILE>      Audio file to write [default: noise.wav]
  -s, --seconds <SECONDS>      Audio file length in seconds [default: 10]
  -r, --rate <RATE>            Audio file sample rate [default: 44100]
      --rms <RMS>              Normalize to RMS value in dBFS [default: -14.0]
      --peak <PEAK>            Normalize to peak value in dBFS (e.g.: -1.0)
  -f, --force                  Overwrite if file already exists
  -h, --help                   Print help
  -V, --version                Print version
```

== Noise generators

=== `OLAP`

*Overlap-and-plus with window function*

The noise is generated by IFFT in chunks of 1 second. Every next chunk has random phases to reduce the pattern effect. To form the final signal, the chunks are blended with overlap of 50%. A synthesis window is applied to suppress boundary discontinuities and reduce modulation artifacts.

=== `PHC`

*Phase Continuation*

The noise is generated by IFFT in chunks of 1 second. Phase correction is unnecessary because all bins are integer harmonics of the chunk length, so phase remains continuous at chunk boundaries. To reduce perceptual periodicity, apply a small stochastic phase perturbation per chunk .
