use anyhow::Result;
use hound::WavWriter;
use rand::RngExt;
use realfft::RealFftPlanner;
use rustfft::num_complex::Complex64;
use std::f64::consts::{PI, TAU};
use std::fs::File;
use std::io::BufWriter;
use log::debug;
use crate::wav::{write_samples, WavMeters};
use crate::{NoiseColor, NormalizationDBFS};

use super::{NoiseGenerator, LOW_FREQUENCIES_THRESHOLD};

/// IFFT Noise with Phase Continuation
///
/// The noise is generated by IFFT in chunks of 1 second. Every next chunk has phases
/// aligned with the previous chunk because all frequencies are integer values!
/// That allows to stitch the chunks together without phase tearing.
///
/// With some probability, in each chunk slightly change the phase to avoid patterns.
///
/// The resulting signal is normalized but only the first chunk is used to calculate the normalization gain.
///
pub struct IFFTPhaseContinuation {
    pub color: NoiseColor,
    pub normalization: NormalizationDBFS,
}

impl NoiseGenerator for IFFTPhaseContinuation {
    fn name(&self) -> &'static str {
        "IFFT with Phase Continuation"
    }

    fn generate(
        &self,
        writer: &mut WavWriter<BufWriter<File>>,
        seconds: usize,
    ) -> Result<WavMeters> {
        let mut meters = WavMeters::default();
        let mut rng = rand::rng();

        let mut planner = RealFftPlanner::<f64>::new();
        let ifft = planner.plan_fft_inverse(writer.spec().sample_rate as usize);

        let mut spectrum = ifft.make_input_vec();
        let mut scratch = ifft.make_scratch_vec();
        let mut signal = ifft.make_output_vec();

        // RustFFT does not normalize outputs. Callers must manually normalize the results.
        let mut normalization_gain: Option<f64> = None;

        // Initial spectrum.
        let initial = {
            let mut spectrum = ifft.make_input_vec();
            let frequencies_num = spectrum.len() - 1; // Do not touch last bin!
            let amplitude_fn = self.color.amplitude_fn();

            spectrum.fill(Complex64::ZERO);
            for (frq, bin) in spectrum[..frequencies_num]
                .iter_mut()
                .enumerate()
                .skip(LOW_FREQUENCIES_THRESHOLD)
            {
                *bin = Complex64::from_polar(amplitude_fn(frq), rng.random::<f64>() * TAU);
            }
            spectrum
        };

        // Generate signal second by second.
        for _ in 0..seconds {
            // The input buffer is used as scratch space, so the contents of input should be considered
            // garbage after calling ifft.process_with_scratch*(). Fill it with original spectrum data.
            // Phase correction is unnecessary because all bins are integer harmonics of the chunk length,
            // so phase remains continuous at chunk boundaries.
            for (current, initial) in spectrum.iter_mut().zip(&initial) {
                let (amplitude, mut phase) = initial.to_polar();
                // Apply a small stochastic phase perturbation per chunk to reduce perceptual periodicity.
                if rng.random::<f64>() < 0.1 {
                    phase += rng.random::<f64>() * PI;
                    phase %= TAU; // [-2 PI, 2 PI]
                }
                *current = Complex64::from_polar(amplitude, phase);
            }

            // Inverse transform a complex spectrum into signal.
            ifft.process_with_scratch(&mut spectrum, &mut signal, &mut scratch)?;

            // Get pre-calculated normalization gain or calculate one based on current signal interval.
            #[allow(clippy::single_match_else)]
            let gain = match normalization_gain {
                Some(gain) => gain,
                None => {
                    let gain = self.normalization.calculate_gain(&signal);
                    normalization_gain = Some(gain);
                    debug!("Normalization gain: {gain}");
                    gain
                }
            };

            // Normalize the signal.
            for s in &mut signal {
                *s *= gain;
            }

            // Write to file.
            write_samples(writer, &signal, Some(&mut meters))?;
        }
        Ok(meters)
    }
}
