use anyhow::Result;
use hound::WavWriter;
use log::debug;
use rand::RngExt;
use realfft::{ComplexToReal, RealFftPlanner};
use rustfft::num_complex::Complex64;
use std::f64::consts::{PI, TAU};
use std::fs::File;
use std::io::BufWriter;
use std::sync::Arc;

use crate::{NoiseColor, NormalizationDBFS};
use crate::wav::{WavMeters, write_samples};

use super::{NoiseGenerator, LOW_FREQUENCIES_THRESHOLD};

#[derive(Copy, Clone)]
pub enum WindowFunction {
    None,
    Sine,
    Hann,
    Hamming,
    Triangular,
}

impl WindowFunction {
    fn get_fn(self) -> fn(usize, usize) -> f64 {
        match self {
            Self::None => |_, _| 1.0,
            Self::Sine => |n, samples| (PI * n as f64 / samples as f64).sin(),
            Self::Hann => |n, samples| (1.0 - (TAU * n as f64 / samples as f64).cos()) / 2.0,
            Self::Hamming => {
                |n, samples| 0.53836 - 0.46164 * (TAU * n as f64 / samples as f64).cos()
            }
            Self::Triangular => |n, samples| 1.0 - (2.0 * n as f64 / samples as f64 - 1.0).abs(),
        }
    }
}

/// IFFT-based noise generator with 50% overlap-add synthesis.
///
/// The noise is generated by IFFT in chunks of 1 second. Every next chunk has random phases
/// to reduce the pattern effect. To form the final signal, the chunks are blended with overlap of 50%.
/// A synthesis window is applied to suppress boundary discontinuities and reduce modulation artifacts.
///
pub struct IFFTOverlapWithWindow {
    pub color: NoiseColor,
    pub normalization: NormalizationDBFS,
    pub window: WindowFunction,
}

impl NoiseGenerator for IFFTOverlapWithWindow {
    fn name(&self) -> &'static str {
        "IFFT with Overlapping Chunks"
    }
    /// Generates a noise signal with specified parameters.
    ///
    /// # Errors
    /// Can fail on IFFT processing or writing samples to file.
    ///
    fn generate(&self, writer: &mut WavWriter<BufWriter<File>>, seconds: usize) -> Result<WavMeters> {
        let mut meters = WavMeters::default();

        let mut planner = RealFftPlanner::<f64>::new();
        let ifft = planner.plan_fft_inverse(writer.spec().sample_rate as usize);

        // Generate the first chunk and split it into two halves.
        let (chunk0_begin, chunk0_end) = split_chunk(
            &self.make_ifft_noise_chunk(ifft.clone())?
        );
        // Write the first half of the first chunk
        //  <...|
        write_samples(writer, &chunk0_begin, Some(&mut meters))?;

        // Write the mix of the half chunks
        //  |...>
        //  <...|
        let last_chunk_end = {
            let mut chunk_n_begin: Vec<f64> = chunk0_end; // second half of chunk N
            let mut chunk_m_end: Vec<f64>;            // first half of chunk N+1
            let half_chunks_num = 2 * (seconds - 1);
            for _ in 0..half_chunks_num {
                let (h_0, h_1) = split_chunk(
                    &self.make_ifft_noise_chunk(ifft.clone())?
                );
                chunk_m_end = h_0;
                let buffer = overlap_chunks(&chunk_n_begin, &chunk_m_end);
                write_samples(writer, &buffer, Some(&mut meters))?;
                chunk_n_begin = h_1;
            }
            chunk_n_begin
        };

        // Write the second half of the last chunk
        //  |...>
        write_samples(writer, &last_chunk_end, Some(&mut meters))?;

        Ok(meters)
    }
}

impl IFFTOverlapWithWindow {
    /// Generate a signal chunk with specified noise color, normalized and window function applied.
    ///
    /// # Errors
    /// Can fail on IFFT processing.
    ///
    #[allow(clippy::needless_pass_by_value)]
    fn make_ifft_noise_chunk(&self, ifft: Arc<dyn ComplexToReal<f64>>) -> Result<Vec<f64>> {
        let mut rng = rand::rng();

        // Initialize spectrum with amplitude and phase values.
        // - amplitude values are calculated based on the noise color.
        // - phase values are random.
        let mut spectrum = ifft.make_input_vec();
        let frequencies_num = spectrum.len() - 1; // Do not touch last bin!
        let amplitude_fn = self.color.amplitude_fn();

        spectrum.fill(Complex64::ZERO);
        for (frq, bin) in spectrum[..frequencies_num]
            .iter_mut()
            .enumerate()
            .skip(LOW_FREQUENCIES_THRESHOLD)
        {
            *bin = Complex64::from_polar(amplitude_fn(frq), rng.random::<f64>() * TAU);
        }

        // Perform inverse FFT and generate a signal chunk using the spectrum.
        let mut signal = ifft.make_output_vec();
        ifft.process(&mut spectrum, &mut signal)?;

        // RustFFT does not normalize outputs. Callers must manually normalize the results.
        let gain = self.normalization.calculate_gain(&signal);
        debug!("Chunk normalization gain: {gain}");

        // Normalize and apply window function.
        let sample_rate = signal.len();
        let window_fn = self.window.get_fn();
        for (n, sample) in signal.iter_mut().enumerate() {
            *sample *= gain * window_fn(n, sample_rate);
        }
        Ok(signal)
    }
}

pub(crate) fn split_chunk(chunk: &[f64]) -> (Vec<f64>, Vec<f64>) {
    let (chunk0_0, chunk0_1) = chunk.split_at_checked(chunk.len() / 2).unwrap();
    (chunk0_0.to_vec(), chunk0_1.to_vec())
}

pub(crate) fn overlap_chunks(chunk1: &[f64], chunk2: &[f64]) -> Vec<f64> {
    assert_eq!(chunk1.len(), chunk2.len());
    chunk1
        .iter()
        .zip(chunk2.iter())
        .map(|(a, b)| a + b)
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    const CHUNK_LEN: usize = 44100;
    const CHUNK_MID: usize = CHUNK_LEN / 2;

    fn make_hann_chunk(size: usize) -> Vec<f64> {
        let window_fn = WindowFunction::Hann.get_fn();
        let mut chunk = vec![0.0f64; size];
        for n in 0..size {
            chunk[n] = window_fn(n, size);
        }
        chunk
    }

    #[test]
    /// Test OLAP for chunks with Hann window function.
    fn test_hamming_window_chunks_overlap() {
        let chunk = make_hann_chunk(CHUNK_LEN);
        let overlap = overlap_chunks(&chunk[CHUNK_MID..], &chunk[..CHUNK_MID]);
        for n in overlap {
            assert!(
                n >= 0.999999999999999f64,
                "Value {} is too small, must be >= 0.999999999999999",
                n
            );
        }
    }

    #[test]
    fn test_hamming_window_many_chunks_overlap() {
        let (chunk0_0, chunk0_1) = split_chunk(&make_hann_chunk(CHUNK_LEN));
        assert_eq!(chunk0_0.len(), CHUNK_MID);
        assert_eq!(chunk0_1.len(), CHUNK_MID);

        let mut chunk_n_1: Vec<f64> = chunk0_1; // second half of chunk N
        let mut chunk_m_0: Vec<f64>; // first half of chunk N+1
        for _ in 0..2 {
            let (c_0, c_1) = split_chunk(&make_hann_chunk(CHUNK_LEN));
            chunk_m_0 = c_0;
            let buffer: Vec<f64> = overlap_chunks(&chunk_n_1, &chunk_m_0);
            for n in buffer {
                assert!(
                    n >= 0.999999999999999f64,
                    "Value {} is too small, must be >= 0.999999999999999",
                    n
                );
            }
            chunk_n_1 = c_1;
        }
    }
}
