use anyhow::Result;
use hound::{SampleFormat, WavSpec, WavWriter};
use log::{debug, info};
use rand::RngExt;
use realfft::{ComplexToReal, RealFftPlanner};
use rustfft::num_complex::Complex64;
use std::f64::consts::TAU;
use std::fs::File;
use std::io::BufWriter;
use std::path::Path;
use std::sync::Arc;

use crate::utils::{amplitude_to_db, overlap_chunks, split_chunk};
use crate::{NoiseColor, NormalizationDBFS, WindowFunction};

#[derive(Default, Debug)]
pub struct WavInfo {
    pub rms: f64,
    pub peak: f64,
}

impl WavInfo {
    pub fn update_max(&mut self, rms: f64, peak: f64) {
        self.rms = self.rms.max(rms);
        self.peak = self.peak.max(peak);
    }

    pub fn rms_db(&self) -> f64 {
        amplitude_to_db(self.rms)
    }

    pub fn peak_db(&self) -> f64 {
        amplitude_to_db(self.peak)
    }

    pub fn print(&self) {
        let peak_db = amplitude_to_db(self.peak);
        if peak_db.is_finite() {
            info!("Peak: {peak_db:.02} dBFS");
        } else {
            info!("Peak: -inf dBFS");
        }

        let rms_db = amplitude_to_db(self.rms);
        if rms_db.is_finite() {
            info!("RMS: {rms_db:.02} dBFS");
        } else {
            info!("RMS: -inf dBFS");
        }
    }
}

/// Frequencies below this threshold are ignored.
const LOW_FREQUENCIES_THRESHOLD: usize = 15;

/// The signal normalization target in dBFS.
const NORMALIZATION_RMS_DBFS: f64 = -14.0;

/// Write a WAV file with noise.
///
/// The noise is generated by IFFT in chunks of `sample_rate` samples (1 second). Every next chunk has random phases
/// to reduce the pattern effect. To form the final signal, the chunks are concatenated with overlap of 50%.
/// Hanning window function is used to blend two chunks without sharp transitions.
///
/// # Errors
/// Can fail on IFFT processing or writing WAV file.
///
pub fn write_with_noise_color(
    color: NoiseColor,
    sample_rate: usize,
    seconds: usize,
    filename: &Path,
    window: WindowFunction,
) -> Result<WavInfo> {
    let spec = WavSpec {
        channels: 1,
        #[allow(clippy::cast_possible_truncation)]
        sample_rate: sample_rate as u32,
        bits_per_sample: 16,
        sample_format: SampleFormat::Int,
    };
    if filename.exists() {
        debug!("Overwriting existing file: {}", filename.display());
    }
    let mut writer = WavWriter::create(filename, spec)?;
    let mut meters = WavInfo::default();
    let mut planner = RealFftPlanner::<f64>::new();
    let ifft = planner.plan_fft_inverse(sample_rate); // 1 sec on current sample rate
    let normalization = NormalizationDBFS::RMS(NORMALIZATION_RMS_DBFS);

    // Generate the first chunk and split it into two halves.
    //
    //  <...|...>
    //
    let (chunk0_0, chunk0_1) = split_chunk(make_noise_chunk(
        ifft.clone(),
        color,
        window,
        normalization,
    )?);

    // Write first half of the first chunk
    //
    //  <...|
    //
    write_samples(&mut writer, &chunk0_0, Some(&mut meters))?;

    // Write the mix of the half chunks
    //
    //  |...>
    //  <...|
    //
    let last_half_chunk = {
        let mut chunk_n_1: Vec<f64> = chunk0_1; // second half of chunk N
        let mut chunk_m_0: Vec<f64>; // first half of chunk N+1
        let half_chunks_num = 2 * (seconds - 1);
        for _ in 0..half_chunks_num {
            let (h_0, h_1) = split_chunk(make_noise_chunk(
                ifft.clone(),
                color,
                window,
                normalization,
            )?);
            chunk_m_0 = h_0;
            let buffer = overlap_chunks(&chunk_n_1, &chunk_m_0);
            write_samples(&mut writer, &buffer, Some(&mut meters))?;
            chunk_n_1 = h_1;
        }
        chunk_n_1
    };

    // Write second half of the last chunk
    //
    //  |...>
    //
    write_samples(&mut writer, &last_half_chunk, Some(&mut meters))?;

    writer.finalize()?;
    Ok(meters)
}

/// Write samples to a WAV file.
///
/// # Errors
/// Can fail on writing to file.
///
fn write_samples(
    writer: &mut WavWriter<BufWriter<File>>,
    samples: &[f64],
    meters: Option<&mut WavInfo>,
) -> Result<()> {
    let mut sqr_sum: f64 = 0.0;
    let mut peak: f64 = 0.0;

    // Write samples and calculate RMS and Peak if required.
    for sample in samples {
        if meters.is_some() {
            sqr_sum += sample.powi(2);
            peak = peak.max(sample.abs());
        }
        #[allow(clippy::cast_possible_truncation)]
        writer.write_sample((sample * f64::from(i16::MAX)) as i16)?;
    }

    // Update RMS and Peak meters.
    if let Some(meters) = meters {
        let rms = (sqr_sum / samples.len() as f64).sqrt();
        meters.update_max(rms, peak);
    }
    Ok(())
}
/// Generate a signal chunk with specified noise color.
///
/// The signal is normalized to `NORMALIZATION_DBFS` dBFS.
/// If `window` is true, the Hann window function is applied.
///
/// # Errors
/// Can fail on IFFT processing.
///
fn make_noise_chunk(
    ifft: Arc<dyn ComplexToReal<f64>>,
    color: NoiseColor,
    window: WindowFunction,
    normalization: NormalizationDBFS,
) -> Result<Vec<f64>> {
    let mut rng = rand::rng();

    // Initialize spectrum with amplitude and phase values.
    // - amplitude values are calculated based on the noise color.
    // - phase values are random.
    let mut spectrum = ifft.make_input_vec();
    let frequencies_num = spectrum.len();
    let amplitude_fn = color.amplitude_fn();

    spectrum.fill(Complex64::ZERO);
    for (frq, bin) in spectrum[..(frequencies_num - 1)]
        .iter_mut()
        .enumerate()
        .skip(LOW_FREQUENCIES_THRESHOLD)
    {
        *bin = Complex64::from_polar(amplitude_fn(frq), rng.random::<f64>() * TAU);
    }

    // Perform inverse FFT and generate a signal chunk using the spectrum.
    let mut signal = ifft.make_output_vec();
    ifft.process(&mut spectrum, &mut signal)?;

    // RustFFT does not normalize outputs. Callers must manually normalize the results.
    let gain = normalization.calculate_gain(&signal);
    debug!("Chunk normalization gain: {gain}");

    // Normalize and apply window function.
    let sample_rate = signal.len();
    let window_fn = window.get_fn();
    for (n, sample) in signal.iter_mut().enumerate() {
        // *sample = (TAU * 331.0 * (n as f64 / sample_rate as f64)).sin() * window_fn(n, sample_rate); // generate a sine wave
        *sample *= gain * window_fn(n, sample_rate);
    }
    Ok(signal)
}
